#!/bin/bash
unzip 01_recv.zip -d 01_recv
unzip 02_send.zip -d 02_send
unzip 03_arp.zip -d 03_arp
unzip 04_icmp.zip -d 04_icmp
unzip 05_arptable.zip -d 05_arptable
unzip 06_netarch.zip -d 06_netarch
unzip 07_udp.zip -d 07_udp
unzip 08_tcp.zip -d 08_tcp
unzip 09_tcp_transmission.zip -d 09_tcp_transmission
unzip 10_tcp_api.zip -d 10_tcp_api
unzip 11_kni.zip -d 11_kni
unzip 12_ddos.zip -d 12_ddos
unzip 13_hash.zip -d 13_hash
unzip 14_tcp_concurrency.zip -d 14_tcp_concurrency
unzip bpf.zip -d bpf
unzip bridgeloadbalancer_plugin.zip -d bridgeloadbalancer_pluginf
unzip dns.zip -d dns
unzip flowtable_plugin.zip -d flowtable_plugin
unzip spdk_server.zip -d spdk_server
unzip vpp_plugin.zip -d vpp_plugin